const sliderData = [
  {
    id: 1,
    title: "DOLOR DE ESPALDA",
    description: "Tratamos tu dolor y trabajamos para recuperar tu movilidad.",
    descriptionTitle: "¿El dolor de espalda limita tu día?",
    longDescription: "El dolor lumbar, la rigidez y las molestias por pasar mucho tiempo sentado pueden afectar tus actividades diarias.",
    url: "/Dolor-espalda.png",
    bgColor: "bg-[#EAF4F5]",
    titleColor: "text-[#0B7F89]",
  },
  {
    id: 2,
    title: "DOLOR DE CUELLO",
    description: "Recupera movilidad y disminuye las molestias.",
    descriptionTitle: "¿Tienes tensión o dolor en el cuello?",
    longDescription: "La tensión muscular, las malas posturas y el trabajo prolongado frente a una computadora pueden provocar dolor y limitar el movimiento.",
    url: "Dolor-cuello.png",
    bgColor: "bg-[#EAF4F5]",
    titleColor: "text-[#0B7F89]",
  },
  {
    id: 3,
    title: "DOLOR DE HOMBRO",
    description: "Evaluamos la causa de tu dolor y diseñamos un tratamiento para ti.",
    descriptionTitle: "¿Te duele al levantar o mover el brazo?",
    longDescription: "El dolor de hombro puede dificultar actividades tan simples como vestirte, alcanzar objetos o dormir.",
    url: "Dolor-hombro.png",
    bgColor: "bg-[#FBE9DF]",
    titleColor: "text-[#E85D24]",
  },
  {
    id: 4,
    title: "DOLOR DE RODILLA",
    description: "Trabajamos para recuperar fuerza, movilidad y función.",
    descriptionTitle: "¿Te duele la rodilla al caminar o subir escaleras?",
    longDescription: "Dolor, inflamación, rigidez o dificultad para moverte pueden afectar tu calidad de vida",
    url: "Dolor-rodilla.png",
    bgColor: "bg-[#EAF4F5]",
    titleColor: "text-[#0B7F89]"

  },
  {
    id: 5,
    title: "CONTRACTURAS Y DOLOR MUSCULAR",
    description: "Te ayudamos a disminuir las molestias y recuperar tu movilidad.",
    descriptionTitle: "¿Sientes tus músculos tensos o cargados?",
    longDescription: "Las contracturas y sobrecargas musculares pueden generar dolor, rigidez y limitar tus movimientos.",
    url: "Dolor-muscular.png",
    bgColor: "bg-[#F0F4E3]",
    titleColor: "text-[#E85D24]",
  },
  {
    id: 6,
    title: "LESIONES DEPORTIVAS",
    description: "Recupera fuerza, movilidad y confianza en tu cuerpo.",
    descriptionTitle: "Vuelve a hacer lo que te gusta.",
    longDescription: "Esguinces, tendinitis, sobrecargas y otras lesiones pueden requerir una recuperación adecuada para volver a tus actividades.",
    url: "rehabilitacion-deportiva.png",
    bgColor: "bg-[#FBE9DF]",
    titleColor: "text-[#E85D24]",
  },
];

export default sliderData;